module.exports.authController = require('./auth.controller')
module.exports.userController = require('./user.controller')
module.exports.liveController = require("./live.controller")
module.exports.categoryController = require("./category.controller")
module.exports.videoController = require("./video.controller")